CREATE DATABASE RestaurantGo
GO

USE RestaurantGo

GO


CREATE TABLE Usuario (
	ID int IDENTITY(1,1) PRIMARY KEY,
	NOMBRE varchar(100)not null,
	CORREO varchar(100)not null,
	CONTRASENA VARCHAR(255)not null
)


CREATE TABLE Restaurante (
	ID int IDENTITY(1,1) PRIMARY KEY,
	NOMBRE varchar(100)not null,
	DIRECCION varchar(1000)not null,
	UBICACION varchar(1000),
	VALORACION int, 
	PRECIO int,
)


CREATE TABLE Comida (
	ID int IDENTITY(1,1) PRIMARY KEY,
	COMIDA varchar(100)not null
)


CREATE TABLE Comentario (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_RESTAURANTE int not null,
	ID_USUARIO int not null,
	COMENTARIO varchar(4000) not null
)
ALTER TABLE COMENTARIO ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
ALTER TABLE COMENTARIO ADD FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE(ID)


CREATE TABLE UsuarioRestaurante (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_USUARIO int not null,
	ID_RESTAURANTE int not null
)	
ALTER TABLE USUARIORESTAURANTE ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
ALTER TABLE USUARIORESTAURANTE ADD FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE(ID)


CREATE TABLE UsuarioComida (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_USUARIO int not null,
	ID_COMIDA int not null
)
ALTER TABLE USUARIOCOMIDA ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
ALTER TABLE USUARIOCOMIDA ADD FOREIGN KEY (ID_COMIDA) REFERENCES COMIDA(ID)


CREATE TABLE RestauranteValoracion (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_USUARIO int not null,
	ID_RESTAURANTE int not null,
	VALOR int not null
)
ALTER TABLE RESTAURANTEVALORACION ADD FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID)
ALTER TABLE RESTAURANTEVALORACION ADD FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE(ID)


CREATE TABLE RestauranteComida (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_RESTAURANTE int not null,
	ID_COMIDA int not null, 
)
ALTER TABLE RESTAURANTECOMIDA ADD FOREIGN KEY (ID_RESTAURANTE) REFERENCES RESTAURANTE(ID)
ALTER TABLE RESTAURANTECOMIDA ADD FOREIGN KEY (ID_COMIDA) REFERENCES COMIDA(ID)
