//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantGo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantGoEntities1 : DbContext
    {
        public RestaurantGoEntities1()
            : base("name=RestaurantGoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comentario> Comentario { get; set; }
        public virtual DbSet<Comida> Comida { get; set; }
        public virtual DbSet<Restaurante> Restaurante { get; set; }
        public virtual DbSet<RestauranteComida> RestauranteComida { get; set; }
        public virtual DbSet<RestauranteValoracion> RestauranteValoracion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioComida> UsuarioComida { get; set; }
        public virtual DbSet<UsuarioRestaurante> UsuarioRestaurante { get; set; }
    }
}
